name: flutter_web_project
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  carousel_slider: ^5.0.0
  flutter:
    sdk: flutter
  flutter_svg: 2.0.9

  http: 1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo.png
    - assets/images/logo.svg
